/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author alunofg
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    TelaCliente telaCliente = null;
    TelaVeiculo telaVeiculo = null;
    TelaServico telaServico = null;
    
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        imnSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        imnCliente = new javax.swing.JMenuItem();
        javax.swing.JMenuItem imnVeiculo = new javax.swing.JMenuItem();
        imnServico = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        imnSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setAutoRequestFocus(false);

        jMenu1.setText("Arquivo");

        imnSair.setText("Sair");
        imnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnSairActionPerformed(evt);
            }
        });
        jMenu1.add(imnSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        imnCliente.setText("Cliente");
        imnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnClienteActionPerformed(evt);
            }
        });
        jMenu2.add(imnCliente);

        imnVeiculo.setText("Veículo");
        imnVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnVeiculoActionPerformed(evt);
            }
        });
        jMenu2.add(imnVeiculo);

        imnServico.setText("Serviço");
        imnServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnServicoActionPerformed(evt);
            }
        });
        jMenu2.add(imnServico);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ajuda");

        imnSobre.setText("Sobre");
        jMenu3.add(imnSobre);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_imnSairActionPerformed

    private void imnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnClienteActionPerformed
        // TODO add your handling code here:
        if(telaCliente == null){
            telaCliente = new TelaCliente();
        }
        telaCliente.setVisible(true);
    }//GEN-LAST:event_imnClienteActionPerformed

    private void imnVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnVeiculoActionPerformed
        // TODO add your handling code here:
         if(telaVeiculo == null){
            telaVeiculo = new TelaVeiculo();
        }
        telaVeiculo.setVisible(true);
    }//GEN-LAST:event_imnVeiculoActionPerformed

    private void imnServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnServicoActionPerformed
        // TODO add your handling code here:
        if(telaServico == null){
            telaServico = new TelaServico();
        }
        telaServico.setVisible(true);
    }//GEN-LAST:event_imnServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem imnCliente;
    private javax.swing.JMenuItem imnSair;
    private javax.swing.JMenuItem imnServico;
    private javax.swing.JMenuItem imnSobre;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
